local mod = get_mod("creature_spawner")

mod.trials_XYZ = {
  -- 1-50 front horde default
  {["x"] = 14.66, ["y"] = 0, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.7, ["y"] = -1.16, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.34, ["y"] = -2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.3, ["y"] = -3, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.45, ["y"] = -4, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.05, ["y"] = -5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.79, ["y"] = 1, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.63, ["y"] = 2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.39, ["y"] = 3, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.59, ["y"] = 4, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.49, ["y"] = 5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.66, ["y"] = 0, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.7, ["y"] = -1, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.34, ["y"] = -2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.3, ["y"] = -3, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.45, ["y"] = -4, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.05, ["y"] = -5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.76, ["y"] = 1, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.63, ["y"] = 2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.39, ["y"] = 3, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.59, ["y"] = 4, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.49, ["y"] = 5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.66, ["y"] = 0, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.7, ["y"] = -1, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.34, ["y"] = -2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.3, ["y"] = -3, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.45, ["y"] = -4, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.05, ["y"] = -5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.76, ["y"] = 1, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.63, ["y"] = 2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.39, ["y"] = 3, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 15.59, ["y"] = 4, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 16.49, ["y"] = 5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.66, ["y"] = 0, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.7, ["y"] = -1, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.34, ["y"] = -2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.3, ["y"] = -3, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.45, ["y"] = -4, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.05, ["y"] = -5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.76, ["y"] = 1, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.63, ["y"] = 2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.39, ["y"] = 3, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.59, ["y"] = 4, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.49, ["y"] = 5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 18.66, ["y"] = -1, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 18.7, ["y"] = -2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 18.34, ["y"] = -3, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 18.3, ["y"] = 1, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 18.45, ["y"] = 2, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 18.05, ["y"] = 3, ["z"] = 0.36, ["rot"] = 90},
  -- 51-100 back horde
  {["x"] = -14.66, ["y"] = 0, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.7, ["y"] = -1.16, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.34, ["y"] = -2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.3, ["y"] = -3, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.45, ["y"] = -4, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.05, ["y"] = -5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.79, ["y"] = 1, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.63, ["y"] = 2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.39, ["y"] = 3, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.59, ["y"] = 4, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.49, ["y"] = 5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.66, ["y"] = 0, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.7, ["y"] = -1, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.34, ["y"] = -2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.3, ["y"] = -3, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.45, ["y"] = -4, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.05, ["y"] = -5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.76, ["y"] = 1, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.63, ["y"] = 2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.39, ["y"] = 3, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.59, ["y"] = 4, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.49, ["y"] = 5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.66, ["y"] = 0, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.7, ["y"] = -1, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.34, ["y"] = -2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.3, ["y"] = -3, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.45, ["y"] = -4, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.05, ["y"] = -5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.76, ["y"] = 1, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.63, ["y"] = 2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.39, ["y"] = 3, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -15.59, ["y"] = 4, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -16.49, ["y"] = 5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.66, ["y"] = 0, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.7, ["y"] = -1, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.34, ["y"] = -2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.3, ["y"] = -3, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.45, ["y"] = -4, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.05, ["y"] = -5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.76, ["y"] = 1, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.63, ["y"] = 2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.39, ["y"] = 3, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.59, ["y"] = 4, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.49, ["y"] = 5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -18.66, ["y"] = -1, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -18.7, ["y"] = -2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -18.34, ["y"] = -3, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -18.3, ["y"] = 1, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -18.45, ["y"] = 2, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -18.05, ["y"] = 3, ["z"] = 0.36, ["rot"] = 270},
  -- 101-150 left horde
  {["x"] = 0, ["y"] = 14.66, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -1.16, ["y"] = 14.7, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -2, ["y"] = 14.34, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -3, ["y"] = 14.3, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -4, ["y"] = 14.45, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -5, ["y"] = 14.05, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 1, ["y"] = 14.79, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 2, ["y"] = 14.63, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 3, ["y"] = 14.39, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 4, ["y"] = 14.59, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 5, ["y"] = 14.49, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 0, ["y"] = 15.66, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -1, ["y"] = 15.7, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -2, ["y"] = 15.34, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -3, ["y"] = 15.3, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -4, ["y"] = 15.45, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -5, ["y"] = 15.05, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 1, ["y"] = 15.76, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 2, ["y"] = 15.63, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 3, ["y"] = 15.39, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 4, ["y"] = 15.59, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 5, ["y"] = 15.49, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 0, ["y"] = 16.66, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -1, ["y"] = 16.7, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -2, ["y"] = 16.34, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -3, ["y"] = 16.3, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -4, ["y"] = 16.45, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -5, ["y"] = 16.05, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 1, ["y"] = 16.76, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 2, ["y"] = 16.63, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 3, ["y"] = 16.39, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 4, ["y"] = 15.59, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 5, ["y"] = 16.49, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 0, ["y"] = 17.66, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -1, ["y"] = 17.7, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -2, ["y"] = 17.34, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -3, ["y"] = 17.3, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -4, ["y"] = 17.45, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -5, ["y"] = 17.05, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 1, ["y"] = 17.76, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 2, ["y"] = 17.63, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 3, ["y"] = 17.39, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 4, ["y"] = 17.59, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 5, ["y"] = 17.49, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -1, ["y"] = 18.66, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -2, ["y"] = 18.7, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -3, ["y"] = 18.34, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 1, ["y"] = 18.3, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 2, ["y"] = 18.45, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 3, ["y"] = 18.05, ["z"] = 0.36, ["rot"] = 180},
  -- 151-200 right horde
  {["x"] = 0, ["y"] = -14.66, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -1.16, ["y"] = -14.7, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -2, ["y"] = -14.34, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -3, ["y"] = -14.3, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -4, ["y"] = -14.45, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -5, ["y"] = -14.05, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 1, ["y"] = -14.79, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 2, ["y"] = -14.63, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 3, ["y"] = -14.39, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 4, ["y"] = -14.59, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 5, ["y"] = -14.49, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 0, ["y"] = -15.66, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -1, ["y"] = -15.7, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -2, ["y"] = -15.34, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -3, ["y"] = -15.3, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -4, ["y"] = -15.45, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -5, ["y"] = -15.05, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 1, ["y"] = -15.76, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 2, ["y"] = -15.63, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 3, ["y"] = -15.39, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 4, ["y"] = -15.59, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 5, ["y"] = -15.49, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 0, ["y"] = -16.66, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -1, ["y"] = -16.7, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -2, ["y"] = -16.34, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -3, ["y"] = -16.3, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -4, ["y"] = -16.45, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -5, ["y"] = -16.05, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 1, ["y"] = -16.76, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 2, ["y"] = -16.63, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 3, ["y"] = -16.39, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 4, ["y"] = -15.59, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 5, ["y"] = -16.49, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 0, ["y"] = -17.66, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -1, ["y"] = -17.7, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -2, ["y"] = -17.34, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -3, ["y"] = -17.3, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -4, ["y"] = -17.45, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -5, ["y"] = -17.05, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 1, ["y"] = -17.76, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 2, ["y"] = -17.63, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 3, ["y"] = -17.39, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 4, ["y"] = -17.59, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 5, ["y"] = -17.49, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -1, ["y"] = -18.66, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -2, ["y"] = -18.7, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -3, ["y"] = -18.34, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 1, ["y"] = -18.3, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 2, ["y"] = -18.45, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 3, ["y"] = -18.05, ["z"] = 0.36, ["rot"] = 0},
  -- 201-204 front ogryn default
  {["x"] = 14.66, ["y"] = -1.5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 14.63, ["y"] = 1.5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.04, ["y"] = -1.5, ["z"] = 0.36, ["rot"] = 90},
  {["x"] = 17.63, ["y"] = 1.5, ["z"] = 0.36, ["rot"] = 90},
  -- 205-208 back ogryn
  {["x"] = -14.66, ["y"] = -1.5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -14.63, ["y"] = 1.5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.04, ["y"] = -1.5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -17.63, ["y"] = 1.5, ["z"] = 0.36, ["rot"] = 270},
  -- 209-212 left ogryn
  {["x"] = -1.5, ["y"] = 14.66, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 1.5, ["y"] = 14.63, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = -1.5, ["y"] = 17.04, ["z"] = 0.36, ["rot"] = 180},
  {["x"] = 1.5, ["y"] = 17.63, ["z"] = 0.36, ["rot"] = 180},
  -- 213-216 right ogryn
  {["x"] = -1.5, ["y"] = -14.66, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 1.5, ["y"] = -14.63, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = -1.5, ["y"] = -17.04, ["z"] = 0.36, ["rot"] = 0},
  {["x"] = 1.5, ["y"] = -17.63, ["z"] = 0.36, ["rot"] = 0},
  -- 217-224 behind pillars, clockwise
  {["x"] = 25.5, ["y"] = 0, ["z"] = 0.3, ["rot"] = 270},
  {["x"] = 18, ["y"] = -18, ["z"] = 0.3, ["rot"] = 315},
  {["x"] = 0, ["y"] = -25.5, ["z"] = 0.3, ["rot"] = 0},
  {["x"] = -18, ["y"] = -18, ["z"] = 0.3, ["rot"] = 45},
  {["x"] = -25.5, ["y"] = 0, ["z"] = 0.3, ["rot"] = 90},
  {["x"] = -18, ["y"] = 18, ["z"] = 0.3, ["rot"] = 135},
  {["x"] = 0, ["y"] = 25.5, ["z"] = 0.3, ["rot"] = 180},
  {["x"] = 18, ["y"] = 18, ["z"] = 0.3, ["rot"] = 225},
  -- 225-232 spawn doors, clockwise
  {["x"] = 29.5, ["y"] = -12.25, ["z"] = 0.3, ["rot"] = 67.5},
  {["x"] = 12.25, ["y"] = -29.5, ["z"] = 0.3, ["rot"] = 22.5},
  {["x"] = -12.25, ["y"] = -29.5, ["z"] = 0.3, ["rot"] = 337.5},
  {["x"] = -29.5, ["y"] = -12.25, ["z"] = 0.3, ["rot"] = 292.5},
  {["x"] = -29.5, ["y"] = 12.25, ["z"] = 0.3, ["rot"] = 247.5},
  {["x"] = -12.25, ["y"] = 29.5, ["z"] = 0.3, ["rot"] = 202.5},
  {["x"] = 12.25, ["y"] = 29.5, ["z"] = 0.3, ["rot"] = 157.5},
  {["x"] = 29.5, ["y"] = 12.25, ["z"] = 0.3, ["rot"] = 112.5},
  -- 233-235 entry portal
  {["x"] = -18.5, ["y"] = 0, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -18.5, ["y"] = -2.5, ["z"] = 0.36, ["rot"] = 270},
  {["x"] = -18.5, ["y"] = 2.5, ["z"] = 0.36, ["rot"] = 270},
  -- 236 center
  {["x"] = 0, ["y"] = 0, ["z"] = 0.36, ["rot"] = 0},
}

mod.trials = {
  {
    ["trial_name"] = "50 groaners",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 2, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 3, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 4, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 5, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 6, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 7, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 8, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 9, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 10, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 11, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 12, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 13, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 14, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 15, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 16, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 17, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 18, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 19, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 20, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 21, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 22, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 23, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 24, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 25, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 26, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 27, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 28, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 29, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 30, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 31, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 32, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 33, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 34, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 35, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 36, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 37, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 38, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 39, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 40, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 41, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 42, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 43, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 44, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 45, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 46, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 47, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 48, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 49, ["breed_name"] = "chaos_newly_infected"},
      {["xyz_id"] = 50, ["breed_name"] = "chaos_newly_infected"},
    }
  },
  {
    ["trial_name"] = "50 poxwalkers",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 2, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 3, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 4, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 5, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 6, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 7, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 8, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 9, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 10, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 11, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 12, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 13, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 14, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 15, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 16, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 17, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 18, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 19, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 20, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 21, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 22, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 23, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 24, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 25, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 26, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 27, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 28, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 29, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 30, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 31, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 32, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 33, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 34, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 35, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 36, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 37, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 38, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 39, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 40, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 41, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 42, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 43, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 44, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 45, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 46, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 47, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 48, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 49, ["breed_name"] = "chaos_poxwalker"},
      {["xyz_id"] = 50, ["breed_name"] = "chaos_poxwalker"},
    }
  },
  {
    ["trial_name"] = "20 scab bruisers",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 2, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 3, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 7, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 8, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 12, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 13, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 14, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 18, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 19, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 23, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 24, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 25, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 29, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 30, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 34, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 35, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 36, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 40, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 41, ["breed_name"] = "renegade_melee"},
    }
  },
  {
    ["trial_name"] = "20 dreg bruisers",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 2, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 3, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 7, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 8, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 12, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 13, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 14, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 18, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 19, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 23, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 24, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 25, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 29, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 30, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 34, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 35, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 36, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 40, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 41, ["breed_name"] = "cultist_melee"},
    }
  },
  {
    ["trial_name"] = "20 scab shooters mix",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 2, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 3, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 7, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 8, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 12, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 13, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 14, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 18, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 19, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 23, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 24, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 25, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 29, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 30, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 34, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 35, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 36, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 40, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 41, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 45, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 48, ["breed_name"] = "renegade_gunner"},
    }
  },
  {
    ["trial_name"] = "20 scab stalkers mix",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 2, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 3, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 7, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 8, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 12, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 13, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 14, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 18, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 19, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 23, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 24, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 25, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 29, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 30, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 34, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 35, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 36, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 40, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 41, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 45, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 48, ["breed_name"] = "renegade_shocktrooper"},
    }
  },
  {
    ["trial_name"] = "20 dreg stalkers mix",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 2, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 3, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 7, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 8, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 12, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 13, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 14, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 18, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 19, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 23, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 24, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 25, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 29, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 30, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 34, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 35, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 36, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 40, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 41, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 45, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 48, ["breed_name"] = "cultist_gunner"},
    }
  },
  {
    ["trial_name"] = "10 scab shotgunners",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 2, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 7, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 12, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 13, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 14, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 18, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 19, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 24, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 29, ["breed_name"] = "renegade_shocktrooper"},
    }
  },
  {
    ["trial_name"] = "10 dreg shotgunners",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 2, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 7, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 12, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 13, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 14, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 18, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 19, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 24, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 29, ["breed_name"] = "cultist_shocktrooper"},
    }
  },
  {
    ["trial_name"] = "8 scab gunners",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 2, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 7, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 23, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 24, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 25, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 29, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 30, ["breed_name"] = "renegade_gunner"},
    }
  },
  {
    ["trial_name"] = "8 dreg gunners",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 2, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 7, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 23, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 24, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 25, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 29, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 30, ["breed_name"] = "cultist_gunner"},
    }
  },
  {
    ["trial_name"] = "6 maulers",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 3, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 8, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 23, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 25, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 30, ["breed_name"] = "renegade_executor"},
    }
  },
  {
    ["trial_name"] = "6 scab ragers",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 3, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 8, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 23, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 25, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 30, ["breed_name"] = "renegade_berzerker"},
    }
  },
  {
    ["trial_name"] = "6 dreg ragers",
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 3, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 8, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 23, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 25, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 30, ["breed_name"] = "cultist_berzerker"},
    }
  },
  {
    ["trial_name"] = "4 bulwarks",
    ["spawn_data"] = {
      {["xyz_id"] = 201, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 202, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_bulwark"},
    }
  },
  {
    ["trial_name"] = "4 reapers",
    ["spawn_data"] = {
      {["xyz_id"] = 201, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 202, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_gunner"},
    }
  },
  {
    ["trial_name"] = "4 crushers",
    ["spawn_data"] = {
      {["xyz_id"] = 201, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 202, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_executor"},
    }
  },
  {
    ["trial_name"] = "Melee pressure - Easy",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 300,
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 162, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 221, ["breed_name"] = "renegade_melee", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 15, ["respawn_timer"] = 3},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 30, ["respawn_timer"] = 1.5},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 16},
    }
  },
  {
    ["trial_name"] = "Melee pressure - Normal",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 360,
    ["spawn_data"] = {
      {["xyz_id"] = 201, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 202, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 162, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 229, ["breed_name"] = "renegade_melee", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 15, ["respawn_timer"] = 2},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 35, ["respawn_timer"] = 0.9},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 12},
    }
  },
  {
    ["trial_name"] = "Melee pressure - Hard",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 360,
    ["spawn_data"] = {
      {["xyz_id"] = 201, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 202, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 1, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 112, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 162, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 174, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 179, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 183, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 184, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 185, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 186, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 187, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 229, ["breed_name"] = "renegade_melee", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 1.5},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 40, ["respawn_timer"] = 0.75},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 8},
    }
  },
  {
    ["trial_name"] = "Melee pressure - Insane",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 360,
    ["spawn_data"] = {
      {["xyz_id"] = 233, ["breed_name"] = "renegade_twin_captain_two"},
      {["xyz_id"] = 201, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 202, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 1, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 112, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 162, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 174, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 179, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 183, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 184, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 185, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 186, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 187, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 229, ["breed_name"] = "renegade_melee", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 1.25},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 40, ["respawn_timer"] = 0.75},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_newly_infected", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 0.9},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 6, ["respawn_timer"] = 7},
    }
  },
  {
    ["trial_name"] = "Ranged pressure - Easy",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 180,
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 104, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 105, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 108, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 109, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 110, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 111, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 121, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 122, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 123, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 125, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 126, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 127, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 128, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 15, ["respawn_timer"] = 1.9},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 16},
    }
  },
  {
    ["trial_name"] = "Ranged pressure - Normal",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 300,
    ["spawn_data"] = {
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 112, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 104, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 105, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 108, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 109, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 110, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 111, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 115, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 116, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 117, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 120, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 121, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 122, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 123, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 125, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 126, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 127, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 128, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 130, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 131, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 132, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 133, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 134, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 135, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 136, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 137, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 162, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 183, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 184, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 185, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 186, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 187, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 25, ["respawn_timer"] = 0.9},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 12},
    }
  },
  {
    ["trial_name"] = "Ranged pressure - Hard",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 300,
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 112, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 104, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 105, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 108, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 109, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 110, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 111, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 115, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 116, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 117, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 120, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 121, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 122, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 123, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 125, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 126, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 127, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 128, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 130, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 131, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 132, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 133, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 134, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 135, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 136, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 137, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 162, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 174, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 179, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 183, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 184, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 185, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 186, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 187, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 35, ["respawn_timer"] = 0.6},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 8},
    }
  },
  {
    ["trial_name"] = "Ranged pressure - Insane",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 360,
    ["spawn_data"] = {
      {["xyz_id"] = 233, ["breed_name"] = "renegade_twin_captain"},
      {["xyz_id"] = 201, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 202, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 112, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 104, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 105, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 108, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 109, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 110, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 111, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 115, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 116, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 117, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 120, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 121, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 122, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 123, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 125, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 126, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 127, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 128, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 130, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 131, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 132, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 133, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 134, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 135, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 136, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 137, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 162, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 174, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 179, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 183, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 184, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 185, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 186, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 187, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 40, ["respawn_timer"] = 0.5},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 6, ["respawn_timer"] = 7},
    }
  },
  {
    ["trial_name"] = "Mixed pressure - Easy",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 300,
    ["spawn_data"] = {
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 5, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 10, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 104, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 105, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 108, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 109, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 110, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 111, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 115, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 116, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 117, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 120, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 121, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 122, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 123, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 125, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 131, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 132, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 133, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 134, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 135, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 136, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 137, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 174, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 179, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 183, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 229, ["breed_name"] = "chaos_newly_infected", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 2.4},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 2.4},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_assault", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 6, ["respawn_timer"] = 12},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 16},
    }
  },
  {
    ["trial_name"] = "Mixed pressure - Normal",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 360,
    ["spawn_data"] = {
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 1, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 5, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 10, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 104, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 105, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 108, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 109, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 110, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 111, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 115, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 116, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 117, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 120, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 121, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 122, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 123, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 125, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 126, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 127, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 128, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 130, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 131, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 132, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 133, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 134, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 135, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 136, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 137, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 174, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 179, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 183, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 184, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 185, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 186, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 187, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 229, ["breed_name"] = "chaos_newly_infected", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 1.6},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 1.6},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_assault", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 8, ["respawn_timer"] = 8},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 12},
    }
  },
  {
    ["trial_name"] = "Mixed pressure - Hard",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 360,
    ["spawn_data"] = {
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 1, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 5, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 6, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 10, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 11, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 112, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 104, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 105, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 108, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 109, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 110, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 111, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 115, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 116, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 117, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 120, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 121, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 122, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 123, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 125, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 126, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 127, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 128, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 130, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 131, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 132, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 133, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 134, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 135, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 136, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 137, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 162, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 174, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 179, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 183, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 184, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 185, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 186, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 187, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 229, ["breed_name"] = "chaos_newly_infected", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 1.2},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 1.2},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_assault", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 8, ["respawn_timer"] = 6},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 8},
    }
  },
  {
    ["trial_name"] = "Mixed pressure - Insane",
    ["trial_ends_by_clear"] = true,
    ["trial_length"] = 360,
    ["spawn_data"] = {
      {["xyz_id"] = 234, ["breed_name"] = "chaos_plague_ogryn", ["weakened"] = true},
      {["xyz_id"] = 235, ["breed_name"] = "chaos_beast_of_nurgle", ["weakened"] = true},
      {["xyz_id"] = 203, ["breed_name"] = "chaos_ogryn_gunner"},
      {["xyz_id"] = 204, ["breed_name"] = "chaos_ogryn_executor"},
      {["xyz_id"] = 1, ["breed_name"] = "chaos_ogryn_bulwark"},
      {["xyz_id"] = 5, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 6, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 10, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 11, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 101, ["breed_name"] = "renegade_executor"},
      {["xyz_id"] = 102, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 107, ["breed_name"] = "renegade_gunner"},
      {["xyz_id"] = 112, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 113, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 114, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 118, ["breed_name"] = "renegade_berzerker"},
      {["xyz_id"] = 119, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 124, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 129, ["breed_name"] = "renegade_shocktrooper"},
      {["xyz_id"] = 104, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 105, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 108, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 109, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 110, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 111, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 115, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 116, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 117, ["breed_name"] = "renegade_melee"},
      {["xyz_id"] = 120, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 121, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 122, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 123, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 125, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 126, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 127, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 128, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 130, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 131, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 132, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 133, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 134, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 135, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 136, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 137, ["breed_name"] = "renegade_rifleman"},
      {["xyz_id"] = 151, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 152, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 157, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 162, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 163, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 164, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 168, ["breed_name"] = "cultist_berzerker"},
      {["xyz_id"] = 169, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 174, ["breed_name"] = "cultist_gunner"},
      {["xyz_id"] = 179, ["breed_name"] = "cultist_shocktrooper"},
      {["xyz_id"] = 154, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 155, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 158, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 159, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 160, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 161, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 165, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 166, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 167, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 170, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 171, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 172, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 173, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 175, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 176, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 177, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 178, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 180, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 181, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 182, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 183, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 184, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 185, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 186, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 187, ["breed_name"] = "cultist_assault"},
      {["xyz_id"] = 229, ["breed_name"] = "chaos_newly_infected", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 1.1},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 3, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 1.1},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_assault", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 12, ["respawn_timer"] = 4},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 6, ["respawn_timer"] = 7},
    }
  },
  {
    ["trial_name"] = "Boss rush - Chaos Spawn",
    ["trial_ends_by_clear"] = true,
    ["spawn_data"] = {
      {["xyz_id"] = 233, ["breed_name"] = "chaos_spawn", ["respawn_timer"] = 15},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 8},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_melee", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 15, ["respawn_timer"] = 2},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_assault", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 6, ["respawn_timer"] = 5},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_executor", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 10},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_berzerker", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 10},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_shocktrooper", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 15},
      {["xyz_id"] = 225, ["breed_name"] = "renegade_gunner", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 2, ["respawn_timer"] = 20},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_newly_infected", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 40, ["respawn_timer"] = 0.75},
    }
  },
  {
    ["trial_name"] = "Boss rush - Beast of Nurgle",
    ["trial_ends_by_clear"] = true,
    ["spawn_data"] = {
      {["xyz_id"] = 233, ["breed_name"] = "chaos_beast_of_nurgle", ["respawn_timer"] = 15},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 8},
      {["xyz_id"] = 225, ["breed_name"] = "cultist_melee", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 15, ["respawn_timer"] = 2},
      {["xyz_id"] = 225, ["breed_name"] = "cultist_assault", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 6, ["respawn_timer"] = 5},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_ogryn_bulwark", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 2, ["respawn_timer"] = 20},
      {["xyz_id"] = 225, ["breed_name"] = "cultist_berzerker", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 10},
      {["xyz_id"] = 225, ["breed_name"] = "cultist_shocktrooper", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 15},
      {["xyz_id"] = 225, ["breed_name"] = "cultist_gunner", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 2, ["respawn_timer"] = 20},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 40, ["respawn_timer"] = 0.75},
    }
  },
  {
    ["trial_name"] = "Hunting Grounds",
    ["trial_length"] = 45,
    ["spawn_data"] = {
      {["xyz_id"] = 1, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 2, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 3, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 7, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 8, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 12, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 13, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 14, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 18, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 19, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 23, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 24, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 25, ["breed_name"] = "cultist_melee"},
      {["xyz_id"] = 29, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 30, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 34, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 35, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 36, ["breed_name"] = "renegade_assault"},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 218, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 223, ["breed_name"] = "chaos_hound_mutator", ["xyz_id_range"] = 1, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 14},
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 2, ["respawn_timer"] = 21},
    }
  },
  {
    ["trial_name"] = "Poxburster Detonator",
    ["trial_length"] = 180,
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "chaos_poxwalker_bomber", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 4},
      {["xyz_id"] = 217, ["breed_name"] = "chaos_poxwalker_bomber", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 3, ["respawn_timer"] = 5},
      {["xyz_id"] = 217, ["breed_name"] = "chaos_hound", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 2, ["respawn_timer"] = 14},
      {["xyz_id"] = 225, ["breed_name"] = "chaos_poxwalker", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 75, ["respawn_timer"] = 0.2},
    }
  },
  {
    ["trial_name"] = "Laser Tag",
    ["trial_length"] = 120,
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "renegade_sniper", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 10, ["respawn_timer"] = 3},
      {["xyz_id"] = 217, ["breed_name"] = "renegade_sniper", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 10, ["respawn_timer"] = 4},
      {["xyz_id"] = 217, ["breed_name"] = "renegade_executor", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 2, ["respawn_timer"] = 19},
      {["xyz_id"] = 217, ["breed_name"] = "cultist_mutant", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 2, ["respawn_timer"] = 39},
    }
  },
  {
    ["trial_name"] = "2 minutes Specials Panic - Easy",
    ["trial_length"] = 120,
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 10, ["respawn_timer"] = 3.75},
    }
  },
  {
    ["trial_name"] = "2 minutes Specials Panic - Normal",
    ["trial_length"] = 120,
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 12, ["respawn_timer"] = 3.25},
    }
  },
  {
    ["trial_name"] = "2 minutes Specials Panic - Hard",
    ["trial_length"] = 120,
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 12, ["respawn_timer"] = 2.75},
    }
  },
  {
    ["trial_name"] = "2 minutes Specials Panic - Very Hard",
    ["trial_length"] = 120,
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 2.25},
    }
  },
  {
    ["trial_name"] = "2 minutes Specials Panic - Insane",
    ["trial_length"] = 120,
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 30, ["respawn_timer"] = 1.5},
    }
  },
  {
    ["trial_name"] = "Endless Specials - Beginner",
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["respawn_timer"] = 3},
    }
  },
  {
    ["trial_name"] = "Endless Specials - Easy",
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 4, ["respawn_timer"] = 5},
    }
  },
  {
    ["trial_name"] = "Endless Specials - Normal",
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 6, ["respawn_timer"] = 4},
    }
  },
  {
    ["trial_name"] = "Endless Specials - Hard",
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 9, ["respawn_timer"] = 3.5},
    }
  },
  {
    ["trial_name"] = "Endless Specials - Very Hard",
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 12, ["respawn_timer"] = 3},
    }
  },
  {
    ["trial_name"] = "Endless Specials - Insane",
    ["spawn_data"] = {
      {["xyz_id"] = 217, ["breed_name"] = "random_special", ["xyz_id_range"] = 7, ["multi_spawn"] = true, ["multi_spawn_cap"] = 20, ["respawn_timer"] = 2.5},
    }
  },
}